name: Metrics

on:
  # Schedule updates every 6 hours
  schedule:
    - cron: "0 */12 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKAPI_TOKEN }}
          plugin_wakatime_days: 360
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os, os-graphs, editor-graphs
          plugin_wakatime_limit: 180
          plugin_wakatime_url: https://wakapi.foxtrot-nas.synology.me/
          plugin_wakatime_user: peseoane
          
          plugin_followup: yes
          plugin_followup_indepth: false

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          
          config_timezone: Europe/Madrid
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_recent_days: 90
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_indepth: true
          plugin_languages_analysis_timeout: 180
          commits_authoring: Pedro Seoane, peseoane, peseoane@users.noreply.github.com
        
